# Generated by Django 3.0.7 on 2020-06-29 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(max_length=30)),
                ('x_coordinate', models.IntegerField(default=0)),
                ('y_coordinate', models.IntegerField(default=0)),
                ('z_coordinate', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='craftapp.Player')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='craftapp.World')),
            ],
        ),
    ]
