# Generated by Django 3.0.7 on 2020-07-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='player',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
